name: x_flutter_kit
description: Flutter项目开发脚手架
version: 1.0.0
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  #  路由
  fluro: ^2.0.5
  #  屏幕适配
  flutter_screenutil: ^5.8.4
  #  图片库
  extended_image: ^8.1.0
  #  bloc状态管理
  flutter_bloc: ^8.1.3
  #  网络库
  dio: ^5.3.2
  #  日志
  logger: ^2.0.1
  #  刷新
  pull_to_refresh: ^2.0.0
  # 本地存储
  shared_preferences: ^2.2.0
  #  toast
  fluttertoast: ^8.2.2
  #  时间格式化
  intl: ^0.18.1
  #  模块通信
  module_bridge: ^1.0.4
  #  版本更新
  flutter_app_update: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  assets:
    - assets/images/